version: "3.8"

services:
  node:
    container_name: node
    image: my-app:1.0
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongoex
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
  # web:
  #   container_name: tasksapp
  #   restart: always
  #   build: .
  #   ports:
  #     - 3000:3000
  #   links:
  #     - mongo
  #   volumes:
  #     - .:/usr/src/app
  # mongo:
  #   container_name: tasksdb
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   logging:
  #     driver: none
